"""empty message

Revision ID: 8c472e088e05
Revises: 
Create Date: 2022-07-13 15:15:52.912498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c472e088e05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_representations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('written_form', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_representations_written_form'), 'form_representations', ['written_form'], unique=True)
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_languages_code'), 'languages', ['code'], unique=True)
    op.create_index(op.f('ix_languages_name'), 'languages', ['name'], unique=True)
    op.create_table('sense_axes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lexicons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lexicons_name'), 'lexicons', ['name'], unique=True)
    op.create_table('orthographies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orthographies_name'), 'orthographies', ['name'], unique=True)
    op.create_table('lexical_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lexicon_id', sa.Integer(), nullable=True),
    sa.Column('part_of_speech', sa.Enum('noun', 'verb', 'adjective', 'adverb', 'auxiliary_verb', 'pronoun', 'proper_noun', 'preposition', 'conjunction', 'interjection', 'numeral', 'determiner', 'particle', 'subordinating_conjunction', 'symbol', 'other', name='partofspeech'), nullable=True),
    sa.ForeignKeyConstraint(['lexicon_id'], ['lexicons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lexical_entries_part_of_speech'), 'lexical_entries', ['part_of_speech'], unique=False)
    op.create_table('lemmas',
    sa.Column('phonetic_form', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lexical_entry_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lexical_entry_id'], ['lexical_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lemmas_phonetic_form'), 'lemmas', ['phonetic_form'], unique=False)
    op.create_table('list_of_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lexical_entry_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lexical_entry_id'], ['lexical_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('senses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lexical_entry_id', sa.Integer(), nullable=True),
    sa.Column('sense_number', sa.Integer(), nullable=True),
    sa.Column('definition', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['lexical_entry_id'], ['lexical_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_senses_definition'), 'senses', ['definition'], unique=False)
    op.create_index(op.f('ix_senses_sense_number'), 'senses', ['sense_number'], unique=False)
    op.create_table('word_forms',
    sa.Column('phonetic_form', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lexical_entry_id', sa.Integer(), nullable=True),
    sa.Column('form_representation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['form_representation_id'], ['form_representations.id'], ),
    sa.ForeignKeyConstraint(['lexical_entry_id'], ['lexical_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_forms_phonetic_form'), 'word_forms', ['phonetic_form'], unique=False)
    op.create_table('sense_sense_axes',
    sa.Column('sense_id', sa.Integer(), nullable=True),
    sa.Column('sense_axis_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sense_axis_id'], ['sense_axes.id'], ),
    sa.ForeignKeyConstraint(['sense_id'], ['senses.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sense_sense_axes')
    op.drop_index(op.f('ix_word_forms_phonetic_form'), table_name='word_forms')
    op.drop_table('word_forms')
    op.drop_index(op.f('ix_senses_sense_number'), table_name='senses')
    op.drop_index(op.f('ix_senses_definition'), table_name='senses')
    op.drop_table('senses')
    op.drop_table('list_of_components')
    op.drop_index(op.f('ix_lemmas_phonetic_form'), table_name='lemmas')
    op.drop_table('lemmas')
    op.drop_index(op.f('ix_lexical_entries_part_of_speech'), table_name='lexical_entries')
    op.drop_table('lexical_entries')
    op.drop_index(op.f('ix_orthographies_name'), table_name='orthographies')
    op.drop_table('orthographies')
    op.drop_index(op.f('ix_lexicons_name'), table_name='lexicons')
    op.drop_table('lexicons')
    op.drop_table('sense_axes')
    op.drop_index(op.f('ix_languages_name'), table_name='languages')
    op.drop_index(op.f('ix_languages_code'), table_name='languages')
    op.drop_table('languages')
    op.drop_index(op.f('ix_form_representations_written_form'), table_name='form_representations')
    op.drop_table('form_representations')
    # ### end Alembic commands ###
