"""empty message

Revision ID: 8dfb1631f7af
Revises: 
Create Date: 2022-04-18 14:55:22.384513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dfb1631f7af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=28), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lexicon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=28), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lexical_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('lexicon_id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=256), nullable=True),
    sa.Column('part_of_speech', sa.Enum('NOUN', 'VERB', 'ADJ', 'ADV', 'PRO', 'PRE', 'CON', 'INT', 'ART', name='partofspeechenum'), nullable=True),
    sa.Column('affix', sa.Enum('PREF', 'SUF', name='partaffixenum'), nullable=True),
    sa.ForeignKeyConstraint(['lexicon_id'], ['lexicon.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('components',
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.Column('composite_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['lexical_entry.id'], ),
    sa.ForeignKeyConstraint(['composite_id'], ['lexical_entry.id'], )
    )
    op.create_table('lexical_form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('written_form', sa.String(length=28), nullable=False),
    sa.Column('alternative_form', sa.String(length=28), nullable=True),
    sa.Column('phonetic_form', sa.String(length=28), nullable=True),
    sa.Column('lexical_entry_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Enum('singular', 'plural', 'collective', 'dual', name='formnumbersenum'), nullable=True),
    sa.Column('gender', sa.Enum('feminine', 'masculine', 'neutral', name='formgendersenum'), nullable=True),
    sa.Column('mood', sa.Enum('indicative', 'imperative', 'conditional', 'subjonctive', 'infinitive', 'participle', 'gerund', name='formmoodsenum'), nullable=True),
    sa.Column('tense', sa.Enum('present', 'past', 'future', 'imperfect', name='formtensesenum'), nullable=True),
    sa.Column('person', sa.Enum('first', 'second', 'third', 'unpersonal', name='formpersonsenum'), nullable=True),
    sa.Column('inflection_type', sa.Enum('conjugation', 'mutation', name='inflectiontypeenum'), nullable=True),
    sa.ForeignKeyConstraint(['lexical_entry_id'], ['lexical_entry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lexical_sense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lexical_entry_id', sa.Integer(), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('disambiguator', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lexical_entry_id'], ['lexical_entry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('translations',
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['lexical_sense.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['lexical_sense.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('translations')
    op.drop_table('lexical_sense')
    op.drop_table('lexical_form')
    op.drop_table('components')
    op.drop_table('lexical_entry')
    op.drop_table('lexicon')
    op.drop_table('language')
    # ### end Alembic commands ###
